### ISSUE TITLE
how to play ai?

### ISSUE THREAD

**Issue by cloudjanak** [amnond/jscrab#1]
can i get all possiable moves that can be played on the current board with starting position and direction
for example you can check below web-site
http://www.lexicalwordfinder.com/?game=Words_With_Friends&layout=1&tiles=gtsfsdf&board=----------------------------------------------------------------------------------------------------------------hello------------------------------------------------------------------------------------------------------------&lexicon=wwf

**Comment by amnond** [comment]
Sorry, I've only seen the question now. It's simple to do what you requested as all possible moves are calculated for the next move.

**Comment by cloudjanak** [comment]
can you make this like above??

**Comment by amnond** [comment]
Unfortunately, I'm too busy with other projects. , but if you look here:

https://github.com/amnond/jscrab/blob/master/src/engine.js#L476

You'll see the line that collects the words that can be played for the computer's term.
Two lines below it you'll see that the words are even logged to the browser console.
It shouldn't be too difficult to do what you want based on this information.
